[project]
name = "manifone-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "librosa>=0.11.0",
    "numpy>=2.2.6",
    "resemblyzer>=0.1.4",
    "scikit-learn>=1.7.1",
    "streamlit>=1.48.0",
]
